[package]
name = "ouisync-swarm"
description = "Utility to spawn multiple ouisync instances on a single machine for testing"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "swarm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true  }
ctrlc = { version = "3.4.1", features = ["termination"] }
os_pipe = "1.1.4"

[target.'cfg(any(target_os = "linux", target_os = "osx"))'.dependencies]
libc = "0.2.126"
